### ISSUE TITLE
What happens when get_outlier_predicate gets a list of plate names?

### ISSUE THREAD

**Issue by constantinpape** [hci-unihd/batchlib#41]
This was brought up by @imagirom in #40:
What happens when `get_outlier_predicate` is passed a list of plate names?
Why is this even supported? The code looks a bit confusing to me:
https://github.com/hci-unihd/batchlib/blob/master/batchlib/outliers/outlier.py#L18-L22

**Comment by wolny** [comment]
sorry @constantinpape and @imagirom I missed that issue.

> What happens when get_outlier_predicate is passed a list of plate names?
Why is this even supported?

it should definitely not be supported to pass a list of plates, since it would lead to errors (i.e. two plates not having unique image names, which is the case for us). The only reason why I put it in the code, is that when I tested the outlier detection integration with the pipeline I've added the `plate_name` attribute in the config https://github.com/hci-unihd/batchlib/blob/master/antibodies/configs/instance_analysis_2.conf and it was always parsed as a list... It's probably just the way `ConfigArgParse` works. Anyway I want to avoid confusion and will make a quick PR with an `assert` that @imagirom suggested.
